name: Deploy CSS via FTP

on:
  push:
    paths:
      - 'custom.css'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy CSS to FTP server
        uses: diegosernadev/ftp-deploy-action@v2  # Using latest stable version (v2)
        with:
          ftp-server: ${{ secrets.FTP_HOST }}  # This will use fs-erytho.easywp.com
          ftp-username: ${{ secrets.FTP_USERNAME }}  # Set in your GitHub Secrets
          ftp-password: ${{ secrets.FTP_PASSWORD }}  # Set in your GitHub Secrets
          local-dir: ./custom.css
          server-dir: /wp-content/uploads/css/
