name: Deploy CSS via SFTP

on:
  push:
    paths:
      - 'custom.css'

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: mikeal/ftp-deploy@v1.2.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: './custom.css'
          target: '/wp-content/uploads/css/'
