name: Deploy via FTP

on:
  push:
    paths:
      - 'custom.css'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: appleboy/ftp-deploy-action@v0.1.8
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: './custom.css'
          target: '/wp-content/uploads/css/'
